# Generated by Django 2.1.5 on 2019-02-16 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop101', '0002_auto_20190216_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(max_length=100),
        ),
    ]
